[package]
name = "orthographic_projector"
version = "0.2.1"
edition = "2021"

[lib]
name = "orthographic_projector"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.6"
num = "0.4.3"
numpy = "0.24.0"

[dependencies.pyo3]
version = "0.24.1"
features = ["extension-module"]
